### ISSUE TITLE
request 200, but return Unauthorized

### ISSUE THREAD

**Issue by im-ling** [SunoAI-API/Suno-API#16]
![image](https://github.com/SunoAI-API/Suno-API/assets/14890206/8fb4a229-dc65-4f22-855b-eeb1702b4fb4)

it was fine yesterday, but today got unauthorized

**Comment by im-ling** [comment]
btw, it keeps saying,  "'NoneType' object has no attribute 'items'"


<img width="1004" alt="image" src="https://github.com/SunoAI-API/Suno-API/assets/14890206/9b9e46aa-86ce-4695-bd22-2021f02a468f">

**Comment by igrbdr1** [comment]
same

**Comment by igrbdr1** [comment]
Looks like they changed some domain names.


Change url here:https://github.com/SunoAI-API/Suno-API/blob/main/cookie.py#L49

to `        url=f"https://clerk.suno.com/v1/client/sessions/{session_id}/tokens?_clerk_js_version=4.72.0-snapshot.vc141245",`

and here: https://github.com/SunoAI-API/Suno-API/blob/main/utils.py#L15
to
`    "Referer": "https://suno.com/",
    "Origin": "https://suno.com",`
    
    and it should work

**Comment by madvas** [comment]
Initially this was my issue, I pulled latest code,  `"NoneType" object has no attribute 'items'` dissapeared, but I'm still getting `{"detail":"Unauthorized"}`. I updated SESSION_ID and COOKIE to my latest.

**Comment by Mcdhcnhk0o0** [comment]
when I got "Unauthorized", just restart the service and everything become ok again

**Comment by madvas** [comment]
ahh it helped! I'd swear I restarted it before, but when I tried now it works, thanks!

**Comment by dvilelaf** [comment]
I'm still getting this error. Should I set the cookie env var like `"__cf_bm=..."` or should I remove the `__cf_bm=` part?

**Comment by JansonChenQ** [comment]
The process of obtaining tokens seems to stop after running for a period of time.
