### ISSUE TITLE
欢迎对接1毛左右

### ISSUE THREAD

**Issue by yuanjie-ai** [SunoAI-API/Suno-API#20]
欢迎对接1毛左右
![image](https://github.com/SunoAI-API/Suno-API/assets/20265321/ecd96fe3-f613-4fe1-bd19-1b67dbc12982)

**Comment by austin2035** [comment]
对接你老母。

**Comment by yuanjie-ai** [comment]
傻逼



---原始邮件---
发件人: "Austin ***@***.***&gt;
发送时间: 2024年4月11日(周四) 中午11:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SunoAI-API/Suno-API] 欢迎对接1毛左右 (Issue #20)




 
对接你老母。
