### ISSUE TITLE
The cookies are not auto-updating

### ISSUE THREAD

**Issue by alessandro-newzoo** [SunoAI-API/Suno-API#28]
Hello,
and thanks for your hard work on this!

The readme says:
> Automatic token maintenance and keep-alive

But I find this not to be the case for me, as every exactly 7 days the API starts returning Unauthorized and I have to go add new cookies manually.

Is anyone else experiencing this? Anything I can do?

Thanks!

**Comment by dvilelaf** [comment]
Same issue here

**Comment by Arslan-Mehmood1** [comment]
Hi, I'm stuck at getting the session_id and cookies. 

we have to go to api.suno.ai right? but it's termporarily unvailable...

![image](https://github.com/SunoAI-API/Suno-API/assets/51626734/9ae6d777-1358-40e0-8a68-ebe3cdcb76f8)

**Comment by alessandro-newzoo** [comment]
@austin2035 has this actually been `completed` or should we take this as `not planned` ? I don't see any commits addressing the issue, correct?
