### ISSUE TITLE
无法链接suno.ai

### ISSUE THREAD

**Issue by kjkjkl** [SunoAI-API/Suno-API#4]
HTTPSConnectionPool(host='clerk.suno.ai', port=443): Max retries exceeded with url: /v1/client/sessions/sess_2eIknoT0bT7smQLtUQiTZ9dTePi/tokens?_clerk_js_version=4.70.5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f15c1444828>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by HonestQiao** [comment]
Maybe, you should use a proxy

**Comment by yuanjie-ai** [comment]
欢迎对接1毛左右
![image](https://github.com/SunoAI-API/Suno-API/assets/20265321/ecd96fe3-f613-4fe1-bd19-1b67dbc12982)
