### ISSUE TITLE
how to use instrumental button

### ISSUE THREAD

**Issue by ZZHbible** [SunoAI-API/Suno-API#5]
<img width="365" alt="WeChat4f174b9b1ffd99c7f5c722fd8e7f7faa" src="https://github.com/SunoAI-API/Suno-API/assets/55887949/e112797b-1a46-4458-97ae-37d058dfa076">

curl -X 'POST' \
  'http://127.0.0.1:8000/generate' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "prompt": "",
  "mv": "chirp-v3-0",
  "title": "hello world",
  "tags": "Pop, folk, easy listening, anime, blues, country, classical"
}'

It will still produce songs with lyrics, are there any parameters that need to be added?

**Comment by Nippytime** [comment]
just to point out, this can happen even in instrumental mode on Suno using any version currently.

**Comment by ZZHbible** [comment]
But I did not see the 'make_instrumental' parameter passed in the API request.

<img width="807" alt="image" src="https://github.com/SunoAI-API/Suno-API/assets/55887949/4f0c9dce-7ebd-4205-b3fc-1f955e0b1848">

**Comment by madvas** [comment]
![image](https://github.com/SunoAI-API/Suno-API/assets/3857155/d8bb3671-e71a-425f-962f-c9163433c169)

I see it, anyways it doesn't seem to be making difference when passing to this library. But what seems to be working, is to leave "prompt" empty and just use "tags".

**Comment by ZZHbible** [comment]
Sure, but there may still be situations where voices are present. At the moment, it seems there's no solution to this. Especially when the tags are particularly long, but the prompt is empty.
